repos:
  - repo: local
    hooks:
      - id: pretty6502
        name: Format 6502/Z80/CP1610/TMS9900/8088 Assembly
        description: This hook uses the pretty6502 pretty-printer to format assembly code.
        entry: pretty6502.sh
        language: script
        files: \.asm$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          [
            --disallow-untyped-calls,
            --disallow-untyped-defs,
            --ignore-missing-imports,
          ]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua-github
