[project]
name = "nn-training"
version = "0.1.0"
description = "Training a small neural network for MNIST classification on a GameBoy"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy<2.0",
    "scikit-learn>=1.7.0",
    "tensorflow>=2.14.0",
    "tflite>=2.18.0",
]
